name: Flatpak Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Pre-release?'
        required: true
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flatpak and flatpak-builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Add Flathub repo
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          flatpak-builder --user --install-deps-from=flathub --repo=repo-dir --force-clean build-dir com.SublimateTheBerry.DistroFox.yml
          flatpak build-bundle repo-dir distrofox.flatpak com.SublimateTheBerry.DistroFox

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: distrofox
          path: distrofox.flatpak

  release-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: distrofox

      - name: Create release (manual)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          files: distrofox.flatpak
          body: |
            New release for DistroFox

  release-tag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: distrofox

      - name: Create release (auto tag)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: distrofox.flatpak
          body: |
            New release for DistroFox
